name: thematic-analysis-dev
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=4.0.0
  - appnope=0.1.3
  - asttokens=2.2.1
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2023.7.22
  - catalogue=2.0.9
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - commonmark=0.9.1
  - confection=0.1.1
  - contourpy=1.0.5
  - cycler=0.11.0
  - cymem=2.0.7
  - cython-blis=0.7.10
  - dataclasses=0.8
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - fastapi=0.103.0
  - fonttools=4.42.1
  - freetype=2.12.1
  - fst-pso=1.8.1
  - funcy=2.0
  - future=0.18.3
  - fuzzytm=2.0.5
  - gensim=4.3.0
  - giflib=5.2.1
  - h11=0.14.0
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib-resources=6.0.1
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.1
  - ipython=8.14.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - kiwisolver=1.4.4
  - langcodes=3.3.0
  - lcms2=2.15
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran5=12.3.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - miniful=0.0.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - munkres=1.1.4
  - murmurhash=1.0.9
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nltk=3.8.1
  - numexpr=2.8.4
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openssl=3.1.2
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pathy=0.10.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - plotly=5.9.0
  - preshed=3.0.8
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pydantic=1.10.12
  - pyfume=0.2.25
  - pygments=2.16.1
  - pyldavis=3.4.1
  - pyparsing=3.1.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2022.7
  - pyzmq=24.0.1
  - readline=8.2
  - regex=2023.8.8
  - requests=2.31.0
  - rich=12.6.0
  - scikit-learn=1.2.2
  - scipy=1.11.1
  - setuptools=68.0.0
  - shellingham=1.5.3
  - simpful=2.11.0
  - six=1.16.0
  - smart_open=5.2.1
  - sniffio=1.3.0
  - soupsieve=2.3.1
  - spacy=3.5.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.41.2
  - srsly=2.4.6
  - stack_data=0.6.2
  - starlette=0.27.0
  - tbb=2021.8.0
  - tenacity=8.2.2
  - textblob=0.15.3
  - thinc=8.1.10
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.9.0
  - typer=0.7.0
  - typing-extensions=4.7.1
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=2.0.4
  - uvicorn=0.23.2
  - vadersentiment=3.3.2
  - wasabi=1.1.2
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
